---
title: "Lab 06 - Conveying the right message through visualisation"
author: [TEAM NAME]
output: github_document
---

### Load packages and data

```{r load-packages, message=FALSE}
library(tidyverse) 
```


### Exercise 1

```{r create-data}
mask_data <- tribble(
  ~date, ~count, ~mask,
  "12/7/2020", 25.2, "mask",
  "13/7/2020", 19.6, "mask",
  "14/7/2020", 19.5, "mask",
  "15/7/2020", 20.2, "mask",
  "16/7/2020", 19.6, "mask",
  "17/7/2020", 19.7, "mask",
  "18/7/2020", 20.3, "mask",
  "19/7/2020", 20, "mask",
  "20/7/2020", 20.5, "mask",
  "21/7/2020", 21.4, "mask",
  "22/7/2020", 19.7, "mask",
  "23/7/2020", 19.9, "mask",
  "24/7/2020", 20.5, "mask",
  "25/7/2020", 19, "mask",
  "26/7/2020", 19.8, "mask",
  "27/7/2020", 17, "mask",
  "28/7/2020", 16.2, "mask",
  "29/7/2020", 16.3, "mask",
  "30/7/2020", 16.4, "mask",
  "31/7/2020", 16, "mask",
  "01/8/2020", 16.1, "mask",
  "02/8/2020", 15.9, "mask",
  "03/8/2020", 16, "mask",
  "12/7/2020", 20.8, "no_mask",
  "13/7/2020", 20.1, "no_mask",
  "14/7/2020", 20.3, "no_mask",
  "15/7/2020", 20.8, "no_mask",
  "16/7/2020", 20.9, "no_mask",
  "17/7/2020", 20.3, "no_mask",
  "18/7/2020", 20.3, "no_mask",
  "19/7/2020", 20.2, "no_mask",
  "20/7/2020", 19.4, "no_mask",
  "21/7/2020", 19.4, "no_mask",
  "22/7/2020", 19.6, "no_mask",
  "23/7/2020", 19.4, "no_mask",
  "24/7/2020", 20.8, "no_mask",
  "25/7/2020", 20.9, "no_mask",
  "26/7/2020", 21.1, "no_mask",
  "27/7/2020", 20.6, "no_mask",
  "28/7/2020", 20.65, "no_mask",
  "29/7/2020", 20.7, "no_mask",
  "30/7/2020", 21, "no_mask",
  "31/7/2020", 19.8, "no_mask",
  "01/8/2020", 20, "no_mask",
  "02/8/2020", 19.8, "no_mask",
  "03/8/2020", 20, "no_mask",
)

```


### Exercise 2

```{r better-viz}
ggplot(mask_data, mapping = aes(date, count, colour = mask, group = mask)) +
  geom_line() +
  theme(axis.text.x = element_text(angle = 90)) +
  labs(x = "Date",
       y = "COVID-19 cases/100K population",
       title = "Kansas COVID-19 7 day rolling average daily cases/100K",
       subtitle = "Source: Kansas Department of Health and Environment",
       colour = "Mask mandate county") +
  scale_colour_discrete(labels = c("Yes", "No"))
```


### Exercise 3

*Add your narrative here.*


### Exercise 4

*Add your narrative here.*
